### ISSUE TITLE
`SdkAutoLoader` always requires OTLP

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-php#1002]
**Describe your environment** 
MacOS
PHP 8.2.5
composer 2.5.5
opentelemetry module

**Steps to reproduce**
Create a new folder with the following composer.json:
```json
{
  "require": {
    "slim/slim": "4.*",
    "slim/psr7": "^1.6",
    "open-telemetry/opentelemetry-auto-slim": "^1.0@beta",
    "open-telemetry/sem-conv": "^1.0@beta",
    "open-telemetry/sdk": "^1.0@beta",
    "symfony/http-client": "^6.3@beta",
    "guzzlehttp/promises": "^1.5",
    "php-http/discovery": "^1.18",
    "psr/http-client-implementation": "*",
    "php-http/guzzle7-adapter": "^1.0"
  },
  "minimum-stability": "beta",
  "config": {
    "allow-plugins": {
      "php-http/discovery": true
    }
  }
}
```

Create a file `index.php` with the following content:

```php
<?php
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require __DIR__ . '/vendor/autoload.php';

$app = AppFactory::create();

$app->get('/', function (Request $request, Response $response, $args) {
    $response->getBody()->write("Hello world!");
    return $response;
});

$app->run();
```

Run the application with 

```
env OTEL_PHP_AUTOLOAD_ENABLED=true OTEL_LOG_LEVEL=debug OTEL_TRACES_EXPORTER=console OTLP_METRICS_EXPORTER=console OTLP_LOGS_EXPORTER=console php -S localhost:8080
```

Send a request with `curl localhost:8080`

**What is the expected behavior?**
Traces, Metrics, Logs being written to the console (or not showing up at all if console exporters are not defined for them)

**What is the actual behavior?**
The following error:

```
<br />
<b>Warning</b>:  Unable to create otlp meter provider: Metric exporter factory not registered for protocol: otlp:  in OpenTelemetry\SDK\Metrics\MeterProviderFactory in <b>vendor/open-telemetry/api/Behavior/LogsMessagesTrait.php</b> on line <b>43</b><br />
<br />
<b>Warning</b>:  Error during opentelemetry initialization: LogRecord exporter factory not defined for: otlp
#0 vendor/open-telemetry/sdk/Logs/ExporterFactory.php(25): OpenTelemetry\SDK\Registry::logRecordExporterFactory('otlp')
#1 vendor/open-telemetry/sdk/Logs/LoggerProviderFactory.php(18): OpenTelemetry\SDK\Logs\ExporterFactory->create()
#2 vendor/open-telemetry/sdk/SdkAutoloader.php(51): OpenTelemetry\SDK\Logs\LoggerProviderFactory->create(Object(OpenTelemetry\SDK\Metrics\MeterProvider))
#3 vendor/open-telemetry/api/Common/Instrumentation/Globals.php(91): OpenTelemetry\SDK\SdkAutoloader::OpenTelemetry\SDK\{closure}(Object(OpenTelemetry\API\Common\Instrumentation\Configurator))
#4 vendor/open-telemetry/api/Common/Instrumentation/Globals.php(47): OpenTelemetry\API\Common\Instrumentation\Globals::globals()
#5vendor/open-telemetry/api/Common/Instrumentation/CachedInstrumentation.php(67): OpenTelemetry\API\Common\Instrumentation\Globals::tracerProvider()
#6 vendor/open-telemetry/opentelemetry-auto-slim/src/SlimInstrumentation.php(39): OpenTelemetry\API\Common\Instrumentation\CachedInstrumentation->tracer()
#7 vendor/slim/slim/Slim/App.php(197): OpenTelemetry\Contrib\Instrumentation\Slim\SlimInstrumentation::OpenTelemetry\Contrib\Instrumentation\Slim\{closure}(Object(Slim\App), Array, 'Slim\\App', 'handle', '/Users/neumanns...', 197)
#8 vendor/slim/slim/Slim/App.php(183): Slim\App->handle(Object(Slim\Psr7\Request))
#9 index.php(15): Slim\App->run()
#10 {main} in <b>vendor/open-telemetry/api/Common/Instrumentation/Globals.php</b> on line <b>93</b><br />
Hello world!%
```

**Additional context**
After doing a little bit of digging it seems that there are some internal metrics & logs being sent via OTLP. I can verify that by installing the otlp package, spinning up a collector and leaving all exporters set to console:

In one window:

```
composer require open-telemetry/exporter-otlp
env OTEL_PHP_AUTOLOAD_ENABLED=true OTEL_LOG_LEVEL=debug OTEL_TRACES_EXPORTER=console OTLP_METRICS_EXPORTER=console OTLP_LOGS_EXPORTER=console php -S localhost:8080
```

In another window:

```
./otelcol-contrib --config=config.yaml
```

After sending a request with `curl localhost:8080` the first window shows me a span using the console exporter for traces, but the other window gives me metrics exported to the collector via OTLP

Doing the same with
```
env OTEL_PHP_AUTOLOAD_ENABLED=true OTEL_LOG_LEVEL=debug OTEL_TRACES_EXPORTER=none OTLP_METRICS_EXPORTER=none OTLP_LOGS_EXPORTER=none php -S localhost:8080
```

gives me a similar result (nothing printed to stdout of the app but metrics being exported to the collector)

**Comment by brettmc** [comment]
Typo in your config: `OTLP_<signal>_EXPORTER` should be `OTEL_<signal>_EXPORTER`

Related to #941, the default exporter selections are `otlp` for traces, metrics, logs: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#exporter-selection and the defaults are being used because of that misconfiguration.

**Comment by svrnm** [comment]
oh, thanks for spotting that! closing this with reason PEBKAC 🤦‍♂️😆
