### ISSUE TITLE
[PHP82] OpenTelemetry + Blackfire extensions results with SegFault

### ISSUE THREAD

**Issue by gkawka** [open-telemetry/opentelemetry-php#1027]
**Environment** 
Working on docker on Linux, production is running on Kubernetes pods 

Both ways to install Blackfire ext with _opentelemetry-1.0.0beta5_ extension result in Segmentation Fault

```Dockerfile
FROM php:8.2-fpm-alpine

RUN apk update

RUN apk add \
    autoconf \
    g++ \
    gcc \
    make \
    bash


RUN pecl install \
    opentelemetry-1.0.0beta5

RUN docker-php-ext-enable \
    opentelemetry

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

# Blackfire agent
RUN bash -c "$(curl -L https://installer.blackfire.io/installer.sh)"
# makes segmentation fault :(
RUN blackfire php:install
```

```Dockerfile
FROM php:8.2-fpm-alpine

RUN apk update

RUN apk add \
    autoconf \
    g++ \
    gcc \
    make \
    bash


RUN pecl install \
    opentelemetry-1.0.0beta5

RUN docker-php-ext-enable \
    opentelemetry

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && architecture=$(uname -m) \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/$architecture/$version \
    && mkdir -p /tmp/blackfire \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8307\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
```

**Steps to reproduce**
1. build and run Dockerfile
2. Run `php -i`

**What is the expected behavior?**
Normal PHP behavoiur

**What is the actual behavior?**
```
/var/www/html # php -i
Segmentation fault (core dumped)
```

**Comment by bobstrecansky** [comment]
We were discussing this in our TC meeting today - does this work with a docker image that isn't alpine?

**Comment by bobstrecansky** [comment]
(We should expect it to work with Alpine, just trying to isolate problem areas)

**Comment by gkawka** [comment]
Hi, thanks for response. Tried Dockerfile from below but it doesn't manage to enable blackfire ext with such warning:

```
Step 5/7 : RUN docker-php-ext-enable blackfire
 ---> Running in 5cf069cb1267
Warning: PHP Startup: Unable to load dynamic library 'blackfire.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so (libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library 'blackfire.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so (libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

```Dockerfile
FROM php:8.2.6-fpm

RUN apt-get update

RUN apt-get install -y \
    autoconf \
    g++ \
    gcc \
    make \
    bash \
    musl-dev \
    sudo


RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && architecture=$(uname -m) \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/$architecture/$version \
    && mkdir -p /tmp/blackfire \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
    && mv /tmp/blackfire/blackfire-*.so  /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8307\n" > $PHP_INI_DIR/conf.d/blackfire.ini \
    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz

RUN docker-php-ext-enable blackfire

RUN pecl install \
    opentelemetry-1.0.0beta5

RUN docker-php-ext-enable \
    opentelemetry

``` 

Also running blackfire installer fails with error _cannot restart blackfire-agent service_

**Comment by brettmc** [comment]
I was able to install opentelemetry + blackfire in alpine, and it segfaults just the same. I was able to get a bit of a backtrace from gdb, but blackfire would not install against a debug build of PHP for better backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x000056122b3707d9 in zend_hash_find ()
(gdb) bt
#0  0x000056122b3707d9 in zend_hash_find ()
#1  0x000056122b370891 in zend_hash_find_ptr_lc ()
#2  0x00007f1bc7c45b13 in find_observers (ht=<optimized out>, n=<optimized out>, pre_hooks=pre_hooks@entry=0x7ffd5f82e920, post_hooks=post_hooks@entry=0x7ffd5f82e958) at /tmp/pear/temp/opentelemetry/otel_observer.c:355
#3  0x00007f1bc7c468ca in resolve_observer (execute_data=0x7f1bc7a127c0) at /tmp/pear/temp/opentelemetry/otel_observer.c:424
#4  observer_fcall_init (execute_data=0x7f1bc7a127c0) at /tmp/pear/temp/opentelemetry/otel_observer.c:446
#5  observer_fcall_init (execute_data=0x7f1bc7a127c0) at /tmp/pear/temp/opentelemetry/otel_observer.c:441
#6  0x000056122b3f4ab7 in ?? ()
#7  0x000056122b03abce in ?? ()
#8  0x000056122b03b59a in ?? ()
#9  0x00007f1bc7c73aea in ?? () from /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so
#10 0x000056122b3cb913 in zend_execute ()
#11 0x00007f1bc7c947dc in bf_load_embedded_code () from /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so
#12 0x00007f1bc7c7b86d in zm_activate_blackfire () from /usr/local/lib/php/extensions/no-debug-non-zts-20220829/blackfire.so
#13 0x000056122b362020 in zend_activate_modules ()
#14 0x000056122b2f5e30 in php_request_startup ()
#15 0x000056122b43ec70 in ?? ()
#16 0x000056122b046061 in ?? ()
#17 0x00007f1bc87749ca in ?? () from /lib/ld-musl-x86_64.so.1
#18 0x00007f1bc87749a2 in ?? () from /lib/ld-musl-x86_64.so.1
#19 0x00007ffd5f83ef10 in ?? ()
#20 0x0000000000000000 in ?? ()
```
