### ISSUE TITLE
EACCESS in host detectors crash opentelemetry initialization "trim(): Argument #1 ($string) must be of type string, bool given"

### ISSUE THREAD

**Issue by pkramme** [open-telemetry/opentelemetry-php#1397]
**Describe your environment** 

Custom hosting environment with a limited environment in which PHP apps are run. Recently did an upgrade from opentelemetry-php/sdk 1.0.8 to 1.1.0.

**Steps to reproduce**
1. Prevent read access to `/etc/machine-id`.

**What is the expected behavior?**
opentelemetry-php/sdk's host detectors should not crash the application, if for any reasons any of the host identifiers cannot be read.

**What is the actual behavior?**
```
OpenTelemetry: [warning] Error during opentelemetry initialization: trim(): Argument #1 ($string) must be of type string, bool given
#0 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/Resource/Detectors/Host.php(56): trim()
#1 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/Resource/Detectors/Host.php(42): OpenTelemetry\SDK\Resource\Detectors\Host->getLinuxId()
#2 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/Resource/Detectors/Host.php(33): OpenTelemetry\SDK\Resource\Detectors\Host->getMachineId()
#3 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/Resource/Detectors/Composite.php(24): OpenTelemetry\SDK\Resource\Detectors\Host->getResource()
#4 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/Resource/ResourceInfoFactory.php(38): OpenTelemetry\SDK\Resource\Detectors\Composite->getResource()
#5 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/SdkAutoloader.php(84): OpenTelemetry\SDK\Resource\ResourceInfoFactory::defaultResource()
#6 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/sdk/SdkAutoloader.php(60): OpenTelemetry\SDK\SdkAutoloader::environmentBasedInitializer()
#7 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/api/Globals.php(93): OpenTelemetry\SDK\SdkAutoloader::OpenTelemetry\SDK\{closure}()
#8 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/api/Globals.php(43): OpenTelemetry\API\Globals::globals()
#9 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/api/Instrumentation/CachedInstrumentation.php(54): OpenTelemetry\API\Globals::tracerProvider()
#10 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/shopware/opentelemetry/src/Instrumentation/ShopwareInstrumentation.php(50): OpenTelemetry\API\Instrumentation\CachedInstrumentation->tracer()
#11 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/shopware/core/Kernel.php(122): Shopware\OpenTelemetry\Instrumentation\ShopwareInstrumentation::Shopware\OpenTelemetry\Instrumentation\{closure}()
#12 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/bin/console(54): Shopware\Core\Kernel->boot()
#13 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/autoload_runtime.php(24): {closure}()
#14 /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/bin/console(17): require_once('...')
#15 {main} in /var/www/hubble_101/dc9f7037-0cdb-4e9c-b723-daf0b6a02eb4/releases/167/vendor/open-telemetry/api/Globals.php(95)
```

**Additional context**

**Comment by pkramme** [comment]
Issue is very likely [here](https://github.com/opentelemetry-php/sdk/compare/1.0.8...1.1.0#diff-5190e8366ac7ed1de0ce9a5d2bfacf6154588c43f93e3ecfa593fb5e022ddbc4R55). This line needs to check if it can actually access the file, because "file is there" not necessarily "can access file".

**Comment by pkramme** [comment]
Thank you very much @brettmc !
