### ISSUE TITLE
Replace Insufficient Stacktrace Function

### ISSUE THREAD

**Issue by ohamuy** [open-telemetry/opentelemetry-php#388]
*Is your feature request related to a problem?*
Currently, the recording of exceptions that happen on any given span uses the built in PHP function getTraceAsString() in the Span class: https://github.com/open-telemetry/opentelemetry-php/blob/b42895ab2b5e548e46ca7dd4828b7dcdcd570044/sdk/Trace/Span.php#L228

This function simply returns a PHP stacktrace of which functions were called prior to the exception being thrown, something similar to the following: 

```
#0 /Users/olihamuy/Desktop/TestBay/test.php(51): grandparent_func()
#1 /Users/olihamuy/Desktop/TestBay/test.php(44): parent_func()
#2 /Users/olihamuy/Desktop/TestBay/test.php(63): child_func()
#3 {main}
```

This gives no insight to where the exception was thrown nor which function threw the original exception or on what line the exception is on. It also does not support chained exceptions. 

*Describe the solution you'd like*
A very strong function was already created by a contributor here: https://www.php.net/manual/en/exception.gettraceasstring.php#114980

This function would result in a much more readable, Java-like stacktrace:
```
Exception: Thrown from grandparent
at grandparent_func(test.php:56)
at parent_func(test.php:51)
at child_func(test.php:44)
at (main)(test.php:62)
```

The function getTraceAsString() should be replaced with the function in the above link. 

@bobstrecansky (https://github.com/bobstrecansky) @alolita

**Comment by ohamuy** [comment]
This has already in the works if you can assign this to me @bobstrecansky
