### ISSUE TITLE
When is InstrumentationLibrarySpans removed in the file proto/otel/Opentelemetry/Proto/Trace/V1/ResourceSpans.php 

### ISSUE THREAD

**Issue by xinfeingxia85** [open-telemetry/opentelemetry-php#805]
**Is your feature request related to a problem?**
There are a lot of deprecated warning logs on the production environment,  because the log level needs to be set the value INFO for application.

```
{"message":"instrumentation_library_spans is deprecated. in /app/vendor/open-telemetry/opentelemetry/proto/otel/Opentelemetry/Proto/Trace/V1/ResourceSpans.php on line 205","context":{},"level":300,"level_name":"WARNING","channel":"local","datetime":"2022-08-23T05:51:48.553502-04:00","extra":{}}
```

**Describe the solution you'd like**
The comment says that this field is deprecated and will be removed after grace period expires on June 15, 2022.

**Comment by brettmc** [comment]
Hi. https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.19.0 was released a couple of weeks ago which removes `instrumentation_library_spans`, but opentelemetry-php is still on v0.16.0. AFAICT our library stopped using the deprecated field a few months back (since v0.0.10) - what version of the library are you using?

**Comment by xinfeingxia85** [comment]
The version of the library is v0.0.14, and this warning starts at v0.0.11.

**Comment by xinfeingxia85** [comment]
> Hi. https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.19.0 was released a couple of weeks ago which removes `instrumentation_library_spans`, but opentelemetry-php is still on v0.16.0. AFAICT our library stopped using the deprecated field a few months back (since v0.0.10) - what version of the library are you using?

The version of the library is v0.0.14, and this warning starts at v0.0.11.

**Comment by brettmc** [comment]
Can you provide a test case (sample code) which triggers the behaviour?

**Comment by xinfeingxia85** [comment]
> Can you provide a test case (sample code) which triggers the behaviour?

Ok,  I will provider it later.

**Comment by xinfeingxia85** [comment]
@brettmc 

The stack trace should be helpful to troubleshoot the problem, as follows:
```
[2022-08-25 05:07:31] local.WARNING: ErrorException: instrumentation_library_spans is deprecated. in /app/vendor/open-telemetry/opentelemetry/proto/otel/Opentelemetry/Proto/Trace/V1/ResourceSpans.php:205
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(418): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Illuminate\Log\Logger))
#1 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): with(Object(Illuminate\Log\Logger), Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError('instrumentation...', '/app/vendor/ope...', 205, 16384)
#3 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'instrumentation...', '/app/vendor/ope...', 205)
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(16384, 'instrumentation...', '/app/vendor/ope...', 205)
#5 /app/vendor/open-telemetry/opentelemetry/proto/otel/Opentelemetry/Proto/Trace/V1/ResourceSpans.php(205): trigger_error('instrumentation...', 16384)
#6 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1364): Opentelemetry\Proto\Trace\V1\ResourceSpans->getInstrumentationLibrarySpans()
#7 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1433): Google\Protobuf\Internal\Message->serializeRepeatedFieldToStream(Object(Google\Protobuf\Internal\FieldDescriptor), Object(Google\Protobuf\Internal\CodedOutputStream))
#8 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1457): Google\Protobuf\Internal\Message->serializeFieldToStream(Object(Google\Protobuf\Internal\CodedOutputStream), Object(Google\Protobuf\Internal\FieldDescriptor))
#9 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php(393): Google\Protobuf\Internal\Message->serializeToStream(Object(Google\Protobuf\Internal\CodedOutputStream))
#10 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/GPBWire.php(573): Google\Protobuf\Internal\GPBWire::writeMessage(Object(Google\Protobuf\Internal\CodedOutputStream), Object(Opentelemetry\Proto\Trace\V1\ResourceSpans))
#11 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1388): Google\Protobuf\Internal\GPBWire::serializeFieldToStream(Object(Opentelemetry\Proto\Trace\V1\ResourceSpans), Object(Google\Protobuf\Internal\FieldDescriptor), true, Object(Google\Protobuf\Internal\CodedOutputStream))
#12 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1433): Google\Protobuf\Internal\Message->serializeRepeatedFieldToStream(Object(Google\Protobuf\Internal\FieldDescriptor), Object(Google\Protobuf\Internal\CodedOutputStream))
#13 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1457): Google\Protobuf\Internal\Message->serializeFieldToStream(Object(Google\Protobuf\Internal\CodedOutputStream), Object(Google\Protobuf\Internal\FieldDescriptor))
#14 /app/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php(1563): Google\Protobuf\Internal\Message->serializeToStream(Object(Google\Protobuf\Internal\CodedOutputStream))
#15 /app/vendor/grpc/grpc/src/lib/AbstractCall.php(117): Google\Protobuf\Internal\Message->serializeToString()
#16 /app/vendor/grpc/grpc/src/lib/UnaryCall.php(39): Grpc\AbstractCall->_serializeMessage(Object(Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceRequest))
#17 /app/vendor/grpc/grpc/src/lib/BaseStub.php(295): Grpc\UnaryCall->start(Object(Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceRequest), Array, Array)
#18 /app/vendor/grpc/grpc/src/lib/BaseStub.php(545): Grpc\BaseStub->Grpc\{closure}('/opentelemetry....', Object(Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceRequest), Array, Array, Array)
#19 /app/vendor/open-telemetry/opentelemetry/proto/otel/Opentelemetry/Proto/Collector/Trace/V1/TraceServiceClient.php(47): Grpc\BaseStub->_simpleRequest('/opentelemetry....', Object(Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceRequest), Array, Array, Array)
#20 /app/vendor/open-telemetry/opentelemetry/src/Contrib/OtlpGrpc/Exporter.php(119): Opentelemetry\Proto\Collector\Trace\V1\TraceServiceClient->Export(Object(Opentelemetry\Proto\Collector\Trace\V1\ExportTraceServiceRequest))
#21 /app/vendor/open-telemetry/opentelemetry/src/SDK/Trace/Behavior/SpanExporterTrait.php(43): OpenTelemetry\Contrib\OtlpGrpc\Exporter->doExport(Array)
#22 /app/vendor/open-telemetry/opentelemetry/src/SDK/Trace/SpanProcessor/SimpleSpanProcessor.php(40): OpenTelemetry\Contrib\OtlpGrpc\Exporter->export(Array)
#23 /app/vendor/open-telemetry/opentelemetry/src/SDK/Trace/Span.php(274): OpenTelemetry\SDK\Trace\SpanProcessor\SimpleSpanProcessor->onEnd(Object(OpenTelemetry\SDK\Trace\Span))
#24 /app/app/Providers/TelemetryServiceProvider.php(113): OpenTelemetry\SDK\Trace\Span->end()
#25 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Providers\TelemetryServiceProvider->App\Providers\{closure}()
#26 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#28 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#29 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#30 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1174): Illuminate\Container\Container->call(Object(Closure))
#31 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(182): Illuminate\Foundation\Application->terminate()
#32 /app/public/index.php(55): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
```
---------------
Pakcage google/protobuf info, as follows:

```
{
            "name": "google/protobuf",
            "version": "v3.21.5",
            "source": {
                "type": "git",
                "url": "https://github.com/protocolbuffers/protobuf-php.git",
                "reference": "70649d33d2b6e8fd0db6d9b6fffc7f46f01f1438"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/protocolbuffers/protobuf-php/zipball/70649d33d2b6e8fd0db6d9b6fffc7f46f01f1438",
                "reference": "70649d33d2b6e8fd0db6d9b6fffc7f46f01f1438",
                "shasum": ""
            },
            "require": {
                "php": ">=7.0.0"
            },
            "require-dev": {
                "phpunit/phpunit": ">=5.0.0"
            },
            "suggest": {
                "ext-bcmath": "Need to support JSON deserialization"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Google\\Protobuf\\": "src/Google/Protobuf",
                    "GPBMetadata\\Google\\Protobuf\\": "src/GPBMetadata/Google/Protobuf"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD-3-Clause"
            ],
            "description": "proto library for PHP",
            "homepage": "https://developers.google.com/protocol-buffers/",
            "keywords": [
                "proto"
            ],
            "support": {
                "source": "https://github.com/protocolbuffers/protobuf-php/tree/v3.21.5"
            },
            "time": "2022-08-09T19:53:56+00:00"
        }
```

**Comment by xinfeingxia85** [comment]
@brettmc 
The code repository link: https://github.com/xinfeingxia85/telemetry-study-demo
The main code files, as follows:
https://github.com/xinfeingxia85/telemetry-study-demo/blob/main/app/Providers/TelemetryServiceProvider.php
https://github.com/xinfeingxia85/telemetry-study-demo/blob/main/app/Http/Controllers/HelloController.php

**Comment by brettmc** [comment]
I've submitted a PR to update protobuf files to the latest version, where instrumentationLibrarySpans is removed. When that gets merged, I'll get you to update to `dev-main` and see if your problem is resolved.

**Comment by xinfeingxia85** [comment]
> I've submitted a PR to update protobuf files to the latest version, where instrumentationLibrarySpans is removed. When that gets merged, I'll get you to update to `dev-main` and see if your problem is resolved.

OK, I will verify later.

**Comment by brettmc** [comment]
dev-main uses latest protobuf files now, can you try it please?

**Comment by xinfeingxia85** [comment]
OK, I will try it today.

**Comment by xinfeingxia85** [comment]
@brettmc  All the warning are gone.

**Comment by brettmc** [comment]
Cool. I think we can close this then. A new release will be out soon.
